### ISSUE TITLE
Add --force to delete to allow remove resource even when actual instance already gone

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#342]
ATM attempt to remove a resource which requires also removal of some instance (cloud instance, etc) would fail if that thing is already remove through other means.  I think we need `--force` option which proceed removing everything it can even if some component (docker container, cloud instance etc) already cannot be found 

```
$> niceman delete test-ec2-west      
Delete the resource 'test-ec2-west'? (ID: i-0368a48188f646b34) (choices: yes, [no], y, n): y

2018-12-18 17:06:25,332 [ERROR  ] An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-0368a48188f646b34' does not exist [client.py:_make_api_call:624] (ClientError) 

$> niceman delete test-ec2-west
Delete the resource 'test-ec2-west'? (ID: i-0368a48188f646b34) (choices: yes, [no], y, n): y

2018-12-18 17:06:33,837 [ERROR  ] An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-0368a48188f646b34' does not exist [client.py:_make_api_call:624] (ClientError) 
```

**Comment by kyleam** [comment]
> I think we need `--force` option which proceed removing everything it can even if some component (docker container, cloud instance etc) already cannot be found

Do you think there even needs to be a `--force` option?  The user is already requesting to remove all the components, so it seems like the sole behavior could be "remove all components, warning if some bit seems to already be gone".

**Comment by yarikoptic** [comment]
I am just afraid that if e.g. I am offline `delete` would fail to delete remove remote resource, and would just fail now, so I could later rerun it when online. If we always remove what we can remove but not necessarily everything - we might end up with those orphans without `niceman` way to get rid of them.  That is why an explicit `--force` could be of help and should (theoretically) be used only sparingly with caution.

**Comment by kyleam** [comment]
I see.  Makes sense.
