### ISSUE TITLE
enable paramiko/fabric logging (into our handlers) if our debug level < DEBUG

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#346]
In the light of #344 it is hard to figure out what is going on in fabric, so we need an easy way to enable its debug output.  I guess the easiest is just to direct their logger into our handlers

**Comment by kyleam** [comment]
I played around with this a bit using

```diff
diff --git a/niceman/log.py b/niceman/log.py
index 190db0d54..27fcb2236 100644
--- a/niceman/log.py
+++ b/niceman/log.py
@@ -252,3 +252,4 @@ def get_initialized_logger(self, logtarget=None):
         return self.lgr

 lgr = LoggerHelper().get_initialized_logger()
+LoggerHelper("paramiko").get_initialized_logger()

```

(I tried to do similar with fabric, but grepping through its codebase suggests it doesn't do that much logging.)

```bash
% niceman create smaug -t ssh -b host=smaug
2019-01-03 19:24:29,555 [INFO   ] Connected (version 2.0, client OpenSSH_7.4p1)
2019-01-03 19:24:29,678 [INFO   ] Authentication (publickey) successful!
2019-01-03 19:24:29,680 [INFO   ] Created the environment smaug

% niceman delete smaug
Delete the resource 'smaug'? (ID: 0e5e89ef-ae95-44fc-a) (choices: yes, [no], y, n): y

2019-01-03 19:24:45,447 [INFO   ] Connected (version 2.0, client OpenSSH_7.4p1)
2019-01-03 19:24:45,573 [INFO   ] Authentication (publickey) successful!
2019-01-03 19:24:45,576 [INFO   ] Deleted the environment smaug
```

I wonder if their INFO level is a bit too verbose for our purposes.

**Comment by yarikoptic** [comment]
you can initialize it  if our log `lgr.getEffectiveLevel() < logging.DEBUG`, so we would get their logs (at any level) only when we go into a "deep debug" (int < 10)

**Comment by kyleam** [comment]
> initialize it if our log `lgr.getEffectiveLevel() < logging.DEBUG`

Yep, given the kind of messages shown in my example above, I agree with that suggestion (which I now notice is included in your title).
