### ISSUE TITLE
RF:  dropping python2 support

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#369]
The verdict was made to drop python2 support in reproman since anyways it is mostly a command line tool anyways, and we interact with the remote sessions from local environment so do not care about what version of python is on remote end. So, possibly to take advantage of python3-only features we are dropping python2 **now** (well, as soon as PR comes in ripping all compatibility shimming).  I think code in PRs shouldn't conflict much if at all.
The question remaining - what minimal version of python3 we would like to support? I guess it would depend on what new features we would like to make use of, and for that we better familiarize us with what is available across python3 versions.   Please chime in posting your favorite (I can only google up some) summaries for "what's new in python 3.x"

**Comment by kyleam** [comment]
Woohoo :>

> The question remaining - what minimal version of python3 we would like to support? I guess it would depend on what new features we would like to make use of

I don't feel strongly about what the minimal minor version is.  I suppose the highest we should consider is probably what's in Debian Stable?  That's 3.5.  

>  and for that we better familiarize us with what is available across python3 versions. Please chime in posting your favorite (I can only google up some) summaries for "what's new in python 3.x"

Well, I'm mostly just googling too :]

The boring things I'd want are all there before 3.4: tuple unpacking (3.0), keyword-only arguments (3.0), and `yield from` (3.3). Some notable modules/features to consider in my view: pathlib (3.4), concurrent.futures (3.2), type hints (3.5), and asyncio (3.4).

So, I dunno.  3.4?

**Comment by yarikoptic** [comment]
explicit string format `f"..."` (3.6)
