### ISSUE TITLE
run: should output --help may be whenever no command was specified?

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#373]
```shell
$> reproman run 
2019-02-14 13:46:01,631 [ERROR  ] 'command' [run.py:__call__:196] (KeyError) 
```

**Comment by kyleam** [comment]
I've gone with just displaying a more informative error rather than showing --help's output when `command=[]`.  This is consistent with the `command=None` case and with `datalad run`.  But let me know if you feel strongly about showing --help's output here, and I'll revisit it.
