### ISSUE TITLE
replace tracing /sbin/iptables with smth else (/bin/bash?)

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#423]
Since we are not tracking symlinks/alternatives (#102 ) ATM, tests started to fail for me locally due to

```
$> ls -l {/etc/alternatives,{/usr,}/sbin}/iptables 
lrwxrwxrwx 1 root root 25 Feb 23 10:58 /etc/alternatives/iptables -> /usr/sbin/iptables-legacy*
lrwxrwxrwx 1 root root 18 Dec 26 11:19 /sbin/iptables -> /usr/sbin/iptables*
lrwxrwxrwx 1 root root 26 Dec 26 11:19 /usr/sbin/iptables -> /etc/alternatives/iptables*
```
and then `dpkg -S` knowing only about the actual one

```shell
$> dpkg -S {/etc/alternatives,{/usr,}/sbin}/iptables /usr/sbin/iptables-legacy 
dpkg-query: no path found matching pattern /etc/alternatives/iptables
dpkg-query: no path found matching pattern /usr/sbin/iptables
dpkg-query: no path found matching pattern /sbin/iptables
iptables: /usr/sbin/iptables-legacy
```

**Comment by kyleam** [comment]
Following 6b495486d (BF(TST): /sbin/iptables is no longer belonging to a package - /bin/ed, 2019-04-11), these could be switched to /bin/ed, but that of course leads to gh-420.  If we decide on something else that we can assume is present, we could change /bin/ed over to that and drop gh-420.

**Comment by yarikoptic** [comment]
oh, interesting -- so I guess that https://github.com/ReproNim/reproman/commit/6b495486dea3e2a6213066b75badd6d5752339ab didn't replace it thoroughly -- will do
