### ISSUE TITLE
venv tracer: reflect in the spec that it was configured to use system-site-packages

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#428]
ATM, if we trace venv created with `--system-site-packages`, we do return information about those system site packages but do nohow mention them in the `venv` record itself.  Then when we get to reinitialize such an environment we would be out of luck since we would need to know either to use that option or not (ATM we do not specify it).

I think we can deduce that if a known package is installed outside of the venv, am I right @kyleam ?

**Comment by kyleam** [comment]
Hmm, IIRC this is already recorded by the `local` field (with a present and true value meaning "not system site package").

Regarding installing system site packages, yes, I punted on this in 8aba36869 (NF: venv: Add basic support for installation, 2018-07-18).

**Comment by yarikoptic** [comment]
ah, `local` field per package!  so we could analyze if any package is not stating that it is local.  gotcha!  I guess my confusion was inflicted also by the fact that I was tracing the built in module `venvs/dev3/lib/python3.7/struct.py` for which there is no package at all ;-)  as we briefly discussed around coffee maker, it would be nice to analyze/mark venv as with system-site-packages while preparing that trace, since later "pruning" of packages (e.g. without files associated) might remove information on either it was installed that way
