### ISSUE TITLE
TODO: run - new orchestrator (or documented workflow) for local datalad run "inplace"

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#460]
Might be just a doc issue.

**use case:** use `niceman run` directly on the host (laptop or smaug), with `condor` submitter, and parallelizing.

sample invocation:

```shell
reproman run --follow -r localshell --sub condor --orc datalad-local-run --bp "sl=10,20,30" sleep "{p[sl]}"
```

The doc for orchestrators (`reproman run --list orchestrators`) talks about "remote" directory/sibling execution for all of them, I guess because primary use case so far was remote execution.  But in my case resource is local.  I wonder if docstring could/should be adjusted to clarify that somehow (e.g. remove "remote" and use "directory/sibling on the resource")

With all `datalad-*` orchestrators, reproman works within a clone of the dataset under `~/.reproman/run-root/<uuid>`.  In my case I want computation to run without any cloning, directly in this dataset.  

I have checked `--list parameters` and decided to try specifying `working_directory`, i.e. my full invocation was

```shel
mkdir out; reproman run --follow -r localshell --sub condor --orc datalad-pair --jp working_directory=$PWD --bp "sl=1,2,3,4,5,6,7,8" bash -c 'sleep 10; touch out/"{p[sl]}"'
```

and I think that did the right thing!  I didn't spot a uuid directory being created under `~/.reproman/run-root/`

**Q to @kyleam : Was that the correct specification to fulfill my usecase?**

**Comment by kyleam** [comment]
There is currently no orchestrator that just runs the command in the current dataset.  The current setup was designed around the usecase of executing on a remote dataset.

**Comment by kyleam** [comment]
> I have checked `--list parameters` and decided to try specifying `working_directory`, i.e. my full invocation was
> 
> [...]
> and I think that did the right thing! I didn't spot a uuid directory being created under `~/.reproman/run-root/`
> 
> **Q to @kyleam : Was that the correct specification to fulfill my usecase?**

My original answer was to the title question, but to answer this question directly: That would be how to specify the local dataset as the "remote" working directory and should prevent any setup under the default `~/.reproman/run-root/` location.  As mentioned in the previous answer, the working directory being the same directory as the local dataset wasn't a usecase that was considered, but it might just work.

**Comment by yarikoptic** [comment]
I have retitled this issue to correspond to the desired functionality.  Either it would require a new orchestrator or could be accomplished by tricking an original, let's pursue it.
