### ISSUE TITLE
make tests runnable but skipping some tests  when a backend dependencies are missing

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#95]
in my case it was `dockerpty` -- without it `pytest niceman` just failed upon imports and didn't run any tests

**Comment by kyleam** [comment]
@mjtravers You could do that with [pytest.importorskip][0] or by adding a condition in reproman/tests/skip.py that looks at `external_versions`:

```python
from reproman.support.external_versions import external_versions
print(external_versions["dockerpty"])
```

[0]: https://docs.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency

**Comment by kyleam** [comment]
@mjtravers I started poking at this a bit already, so I'll take it off your hands.
